### ISSUE TITLE
Testing in Create React App

### ISSUE THREAD

**Issue by allengordon011** [lukeed/sockette#21]
I built my app starting with the convenient create-react-app. It comes with Jest built in for testing. However, I can't run any tests because of the following error:
```
ReferenceError: WebSocket is not defined
      
      at Object.<anonymous>.module.exports.r.open (node_modules/sockette/dist/sockette.js:1:508)
      at new Object.<anonymous>.module.exports (node_modules/sockette/dist/sockette.js:1:745)
      at new NTWebSocket (src/server.js:14:15)
      at Object.<anonymous> (src/index.js:22:17)
      at Object.<anonymous> (src/test/App.test.js:21:14)
```

**Comment by only-cliches** [comment]
You can't run websocket libraries in NodeJS.  This isn't a limitation of sockette but of NodeJS itself, it just doesn't provide the same WebSocket api as browsers.

You need to adjust your tests or your application to use a different or emulated code path depending on the environment it's in.

Something like this:

```js
if (typeof WebSocket !== "undefined") {
   // Do real WebSocket stuff in the browser
} else {
   // We're in NodeJS, no WebSocket API!
}
```

**Comment by lukeed** [comment]
What @ClickSimply said is correct. There's no `WebSocket` built-in within Node.js -- you have to either add the conditional check, or include a mock/stand-in for your tests.

You can use something like `ws` or `uws` as your Node.js version of `WebSocket`. Here's a [usage example](https://github.com/websockets/ws#usage-examples) from the `ws` README.

Personally, I haven't tested Sockette extending from WebSocket replacement (since this is a browser module). But if I ever get around to writing tests for this library, I'd use either of those replacements to do so.

Hope that helps!

**Comment by allengordon011** [comment]
Thanks @ClickSimply , I only saw your response after this issue was closed. Thanks also to @lukeed.
