### ISSUE TITLE
Able to detect network lost?

### ISSUE THREAD

**Issue by yoonwaiyan** [lukeed/sockette#53]
Hi there, sorry if my issue is silly, I'm still amateur in websockets handling. I'm facing a problem where I couldn't disconnect properly using sockette when the network is offline. I'm currently using sockette to connect with my Websocket API using AWS API Gateway, everything seems fine except when I realized that the connections created by the gateway isn't always being disconnected thus leaving many dead connection records in my DynamoDB. This is how I replicate the issue:

1. Open new tab and access to my website with websocket connection, wait until it's connected
2. Turn off my laptop WiFi connection, to simulate offline connection
3. Close the tab
4. Turn on my laptop WiFi connection

I'm wondering do Sockette handles such situation, at least have a callback when offline connection is detected? If it's already available, how can I modify my code to cater for that? This is my code in React:

```
useEffect(
  () => {
    if (isProduction) {
      webSocket = new Sockette(webSocketUrlFor(userId), {
        timeout: 5e3,
        onopen: e => console.log('Connected', e),
        onmessage: onReceivedMessage,
        onreconnect: () => console.log('Reconnecting...'),
        onmaximum: e => console.log('Stop Attempting!', e),
        onclose: e => {
          console.log('Closed connection. Reconnecting...', e);
          webSocket.reconnect();
        },
        onerror: e => console.log('Error:', e)
      });

      return () => {
        webSocket.close();
      };
    }
  },
  [userId]
);
```

**Comment by lukeed** [comment]
Hey, not silly!

In this case you would have to catch/listen for the disconnection from the server side's point of view. This is because your client unexpectedly shuts down (for whatever reason), so there's no chance to send a `ws.close()` or even a `Going Away` code. The network is gone so there's no ability to send anything.

I don't use AWS for WS, so I can't help much beyond linking to what looks to be [relevant](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-websocket-api-route-keys-connect-disconnect.html#apigateway-websocket-api-routes-about-disconnect) [docs](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-how-to-call-websocket-api-connections.html).

Hope that helps!
