### ISSUE TITLE
Bind with React and Preact

### ISSUE THREAD

**Issue by farskid** [lukeed/sockette#7]
Hey there.

First of all, thanks for a great work on this library.

So I created a library to bind Sockette to React and Preact at the same time. I wanted to reduce the hassle of switching the component from the two library. the idea just lands in creating a component factory.

You can check it out [here](https://github.com/farskid/sockette-component).

I was wondering, is there any chance we can merge it with your version of preact-sockette?

This way both React and Preact users can enjoy using this component. and Yes, I am aware of compat libraries :) I just think creating a factory for components is a better way since it can also be used in other alternatives such as Inferno too.

and probably a good idea that all the components that we create for these libraries, be written as factories.

**Comment by lukeed** [comment]
Hey~! I actually like `preact-sockette` the way it is, sorry 😕 

Setting up aliases for Preact vs React vs Inferno is a one-time configuration that applies globally to a project. AKA, you'd pay more of a cost re-initializing a bunch of factories at runtime, rather than just setting up the proper aliases at build-time. 

My component is also basic enough that it already works in any lib that claims to be React-like. I also think that the `ws` key belongs in context, not state. 

You're more than welcome to continue development on your component -- I'm sure others prefer the factory-approach for their projects, too!

Thank you so much though! Happy to see adoption like this 😃
